# We used debian:jessie below to build a docker image,
# then use that image below to speed up GitHub Actions.
#
#FROM debian:jessie
FROM dockerglacier/action-perlcritic:base

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git unzip wget jq cpanminus build-essential make \
    libtest-perl-critic-perl \
    libalgorithm-c3-perl \
    libalgorithm-diff-perl \
    libalgorithm-diff-xs-perl \
    libalgorithm-merge-perl \
    libapache2-mod-perl2 \
    libapache2-reload-perl \
    libapache-dbi-perl \
    libappconfig-perl \
    libapt-pkg-perl \
    libauthen-sasl-perl \
    libb-hooks-endofscope-perl \
    libbit-vector-perl \
    libboolean-perl \
    libbsd-resource-perl \
    libcache-memcached-perl \
    libcarp-clan-perl \
    libcgi-fast-perl \
    libcgi-pm-perl \
    libclass-c3-perl \
    libclass-c3-xs-perl \
    libclass-factory-util-perl \
    libclass-inspector-perl \
    libclass-load-perl \
    libclass-load-xs-perl \
    libclass-methodmaker-perl \
    libclass-singleton-perl \
    libclass-tiny-perl \
    libclone-perl \
    libcommon-sense-perl \
    libconfig-any-perl \
    libconfig-general-perl \
    libconfig-tiny-perl \
    libconvert-asn1-perl \
    libconvert-ber-perl \
    libcrypt-openssl-bignum-perl \
    libcrypt-openssl-rsa-perl \
    libcrypt-rijndael-perl \
    libdata-alias-perl \
    libdata-optlist-perl \
    libdata-serializer-perl \
    libdata-stream-bulk-perl \
    libdata-visitor-perl \
    libdate-calc-perl \
    libdate-calc-xs-perl \
    libdatetime-event-ical-perl \
    libdatetime-event-recurrence-perl \
    libdatetime-format-builder-perl \
    libdatetime-format-flexible-perl \
    libdatetime-format-http-perl \
    libdatetime-format-ical-perl \
    libdatetime-format-natural-perl \
    libdatetime-format-strptime-perl \
    libdatetime-locale-perl \
    libdatetime-perl \
    libdatetime-set-perl \
    libdatetime-timezone-perl \
    libdatetimex-easy-perl \
    libdbd-mysql-perl \
    libdbi-perl \
    libdevel-caller-perl \
    libdevel-globaldestruction-perl \
    libdevel-lexalias-perl \
    libdevel-partialdump-perl \
    libdevel-stacktrace-perl \
    libdevel-symdump-perl \
    libdigest-hmac-perl \
    libdigest-md5-file-perl \
    libdigest-sha-perl \
    libdist-checkconflicts-perl \
    libdpkg-perl \
    libemail-date-format-perl \
    libemail-valid-perl \
    libencode-locale-perl \
    liberror-perl \
    libeval-closure-perl \
    libev-perl \
    libexpect-perl \
    libexporter-lite-perl \
    libfax-hylafax-client-perl \
    libfcgi-perl \
    libfile-basedir-perl \
    libfile-desktopentry-perl \
    libfile-fcntllock-perl \
    libfile-find-rule-perl \
    libfile-listing-perl \
    libfile-mimeinfo-perl \
    libfile-next-perl \
    libfile-sharedir-perl \
    libfile-slurp-perl \
    libfont-afm-perl \
    libgssapi-perl \
    libhash-flatten-perl \
    libhtml-format-perl \
    libhtml-formattext-withlinks-perl \
    libhtml-formfu-perl \
    libhtml-form-perl \
    libhtml-parser-perl \
    libhtml-scrubber-perl \
    libhtml-strip-perl \
    libhtml-tagset-perl \
    libhtml-tokeparser-simple-perl \
    libhtml-tree-perl \
    libhttp-cookies-perl \
    libhttp-daemon-perl \
    libhttp-date-perl \
    libhttp-message-perl \
    libhttp-negotiate-perl \
    libimage-magick-perl \
    libimage-magick-q16-perl \
    libio-html-perl \
    libio-interactive-perl \
    libio-pty-perl \
    libio-socket-inet6-perl \
    libio-socket-ip-perl \
    libio-socket-socks-perl \
    libio-socket-ssl-perl \
    libio-stty-perl \
    libipc-run-perl \
    libipc-shareable-perl \
    libjson-xs-perl \
    liblist-allutils-perl \
    liblist-moreutils-perl \
    liblocale-gettext-perl \
    liblog-dispatch-perl \
    liblog-log4perl-perl \
    liblog-trace-perl \
    liblwp-mediatypes-perl \
    liblwp-protocol-https-perl \
    liblwp-useragent-determined-perl \
    libmail-sendmail-perl \
    libmailtools-perl \
    libmath-bigint-perl \
    libmime-lite-html-perl \
    libmime-lite-perl \
    libmime-types-perl \
    libmodule-implementation-perl \
    libmodule-pluggable-perl \
    libmodule-runtime-conflicts-perl \
    libmodule-runtime-perl \
    libmojolicious-perl \
    libmojo-server-fastcgi-perl \
    libmoose-perl \
    libmoosex-aliases-perl \
    libmoosex-strictconstructor-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-perl \
    libmro-compat-perl \
    libnamespace-autoclean-perl \
    libnamespace-clean-perl \
    libnet-amazon-s3-perl \
    libnet-dbus-perl \
    libnet-dns-perl \
    libnet-domain-tld-perl \
    libnet-http-perl \
    libnet-ip-perl \
    libnet-ldap-perl \
    libnet-sftp-foreign-perl \
    libnet-smtp-ssl-perl \
    libnet-ssleay-perl \
    libnumber-compare-perl \
    libnumber-format-perl \
    libpackage-deprecationmanager-perl \
    libpackage-stash-perl \
    libpackage-stash-xs-perl \
    libpadwalker-perl \
    libparams-classify-perl \
    libparams-util-perl \
    libparams-validate-perl \
    libparse-recdescent-perl \
    libpath-class-perl \
    libperl4-corelibs-perl \
    libreadonly-perl \
    libregexp-common-perl \
    libset-infinite-perl \
    libsocket6-perl \
    libstring-crc32-perl \
    libsub-exporter-perl \
    libsub-exporter-progressive-perl \
    libsub-identify-perl \
    libsub-install-perl \
    libsub-name-perl \
    libsub-uplevel-perl \
    libsys-hostname-long-perl \
    libtask-weaken-perl \
    libtemplate-perl \
    libterm-encoding-perl \
    libterm-progressbar-perl \
    libterm-progressbar-quiet-perl \
    libterm-progressbar-simple-perl \
    libterm-readkey-perl \
    libtest-assertions-perl \
    libtest-exception-perl \
    libtest-mockobject-perl \
    libtest-warn-perl \
    libtext-asciitable-perl \
    libtext-charwidth-perl \
    libtext-csv-perl \
    libtext-csv-xs-perl \
    libtext-glob-perl \
    libtext-iconv-perl \
    libtext-wrapi18n-perl \
    libtie-ixhash-perl \
    libtie-toobject-perl \
    libtimedate-perl \
    libtime-duration-parse-perl \
    libtime-duration-perl \
    libtry-tiny-perl \
    libuniversal-can-perl \
    libuniversal-isa-perl \
    liburi-perl \
    libvariable-magic-perl \
    libwww-perl \
    libwww-robotrules-perl \
    libx11-protocol-perl \
    libxml-dom-perl \
    libxml-dom-xpath-perl \
    libxml-libxml-perl \
    libxml-namespacesupport-perl \
    libxml-parser-perl \
    libxml-perl \
    libxml-regexp-perl \
    libxml-sax-base-perl \
    libxml-sax-expat-perl \
    libxml-sax-perl \
    libxml-simple-perl \
    libxml-twig-perl \
    libxml-xpathengine-perl \
    libyaml-libyaml-perl

COPY debdir /debdir

ENV REVIEWDOG_VERSION=v0.10.0
RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}

ADD .perlcriticrc /.perlcriticrc

#RUN wget -O /cpanfile -q https://raw.githubusercontent.com/gitglacier/nf-web/master/cpanfile
#RUN cpanm --installdeps /cpanfile

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
